app = "nightly-npubcash"
primary_region = "ams"

[build]
  [build.args]
    HOSTNAME = "https://npuby.cash"

[env]
HOSTNAME = "https://npuby.cash"
LNURL_MAX_AMOUNT = "100000000"
LNURL_MIN_AMOUNT = "1000"
MINTURL = "https://mint.minibits.cash/Bitcoin"
LOG_LEVEL = "debug"
USERNAME_MINT = "https://mint.minibits.cash/Bitcoin"
USERNAME_COST = "5000"

[http_service]
auto_start_machines = true
auto_stop_machines = "off"
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = ["app"]

[mounts]
source = "nighly_npc_data"
destination = "/data"

[[vm]]
size = "shared-cpu-1x"
