import { DatabaseAdapter } from "./database/adapter";
import { logger } from "@/utils/logger";

export interface Migration {
  id: string;
  sql?: {
    postgres: string[];
    sqlite: string[];
  };
  execFn?: (db: DatabaseAdapter) => Promise<void>;
}

async function rejectUnmigratedV2Database(db: DatabaseAdapter): Promise<void> {
  if (db.type !== "postgres") {
    return;
  }

  const result = await db.query<{ has_v2_migrations: boolean }>(`
    SELECT EXISTS (
      SELECT 1
      FROM information_schema.tables
      WHERE table_schema = current_schema()
        AND table_name = 'pgmigrations'
    ) AS has_v2_migrations
  `);

  if (!result.rows[0]?.has_v2_migrations) {
    return;
  }

  throw new Error(`Detected an unmigrated v2 PostgreSQL database (pgmigrations exists).
Refusing to modify it in place. Stop every v2 server instance, create a separate empty v3 database, and run:

cd packages/server
bun run migrate:v2-postgres -- \\
  --source "$V2_DATABASE_URL" \\
  --target "$V3_DATABASE_URL" \\
  --confirm-v2-stopped \\
  --report migration-report.json

See the "Migrating a v2 PostgreSQL database" runbook in README.md.`);
}

export async function runMigrations(db: DatabaseAdapter): Promise<void> {
  await rejectUnmigratedV2Database(db);

  // Create migrations tracking table
  const createMigrationsTable =
    db.type === "postgres"
      ? `CREATE TABLE IF NOT EXISTS _migrations (
           id TEXT PRIMARY KEY,
           applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
         );`
      : `CREATE TABLE IF NOT EXISTS _migrations (
           id TEXT PRIMARY KEY,
           applied_at TEXT NOT NULL DEFAULT (datetime('now'))
         );`;

  await db.query(createMigrationsTable);

  const result = await db.query<{ id: string }>("SELECT id FROM _migrations");
  const applied = new Set(result.rows.map((row) => row.id));

  for (const migration of migrations) {
    if (applied.has(migration.id)) {
      logger.debug(`Migration ${migration.id} already applied, skipping`);
      continue;
    }

    logger.info(`Running migration: ${migration.id}`);

    if (migration.sql) {
      for (const statement of migration.sql[db.type]) {
        await db.query(statement);
      }
    }

    if (migration.execFn) {
      await migration.execFn(db);
    }

    await db.query("INSERT INTO _migrations (id) VALUES ($1)", [migration.id]);

    logger.info(`Migration ${migration.id} completed`);
  }
}

export const migrations: Migration[] = [
  {
    id: "001_v3_baseline",
    sql: {
      postgres: [
        `CREATE TABLE IF NOT EXISTS l_users (
           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
           created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
           pubkey TEXT NOT NULL UNIQUE,
           name TEXT UNIQUE,
           mint_url TEXT,
           lock_quote BOOLEAN DEFAULT FALSE
         )`,
        `CREATE TABLE IF NOT EXISTS mint_quotes (
           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
           created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
           unit TEXT NOT NULL,
           mint_url TEXT NOT NULL,
           payment_request TEXT NOT NULL,
           quote_id TEXT NOT NULL,
           expires_at TIMESTAMPTZ NOT NULL,
           amount INTEGER NOT NULL,
           pubkey TEXT NOT NULL,
           state TEXT NOT NULL,
           paid_at TIMESTAMPTZ,
           serialized_zap_request TEXT,
           locked BOOLEAN NOT NULL DEFAULT FALSE
         )`,
        "CREATE INDEX IF NOT EXISTS idx_mint_quotes_quote_id ON mint_quotes(quote_id)",
        `CREATE TABLE IF NOT EXISTS mints (
           mint_url TEXT PRIMARY KEY,
           last_checked TIMESTAMPTZ NOT NULL,
           mint_info JSONB NOT NULL
         )`,
        "CREATE INDEX IF NOT EXISTS idx_mints_mint_url ON mints(mint_url)",
        `CREATE TABLE IF NOT EXISTS proofs (
           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
           amount INTEGER NOT NULL,
           keyset_id TEXT NOT NULL,
           secret TEXT NOT NULL,
           "C" TEXT NOT NULL,
           state TEXT NOT NULL
         )`,
      ],
      sqlite: [
        `CREATE TABLE IF NOT EXISTS l_users (
           id INTEGER PRIMARY KEY AUTOINCREMENT,
           created_at TEXT NOT NULL DEFAULT (datetime('now')),
           pubkey TEXT NOT NULL UNIQUE,
           name TEXT UNIQUE,
           mint_url TEXT,
           lock_quote INTEGER DEFAULT 0
         )`,
        `CREATE TABLE IF NOT EXISTS mint_quotes (
           id INTEGER PRIMARY KEY AUTOINCREMENT,
           created_at TEXT NOT NULL DEFAULT (datetime('now')),
           unit TEXT NOT NULL,
           mint_url TEXT NOT NULL,
           payment_request TEXT NOT NULL,
           quote_id TEXT NOT NULL,
           expires_at TEXT NOT NULL,
           amount INTEGER NOT NULL,
           pubkey TEXT NOT NULL,
           state TEXT NOT NULL,
           paid_at TEXT,
           serialized_zap_request TEXT,
           locked INTEGER NOT NULL DEFAULT 0
         )`,
        "CREATE INDEX IF NOT EXISTS idx_mint_quotes_quote_id ON mint_quotes(quote_id)",
        `CREATE TABLE IF NOT EXISTS mints (
           mint_url TEXT PRIMARY KEY,
           last_checked TEXT NOT NULL,
           mint_info TEXT NOT NULL
         )`,
        "CREATE INDEX IF NOT EXISTS idx_mints_mint_url ON mints(mint_url)",
        `CREATE TABLE IF NOT EXISTS proofs (
           id INTEGER PRIMARY KEY AUTOINCREMENT,
           amount INTEGER NOT NULL,
           keyset_id TEXT NOT NULL,
           secret TEXT NOT NULL,
           C TEXT NOT NULL,
           state TEXT NOT NULL
         )`,
      ],
    },
  },
  {
    id: "002_mint_quote_monitoring",
    sql: {
      postgres: [
        `CREATE TABLE IF NOT EXISTS mint_quote_mint_retries (
           mint_url TEXT PRIMARY KEY,
           failure_count INTEGER NOT NULL,
           next_attempt_at TIMESTAMPTZ NOT NULL,
           last_failure_at TIMESTAMPTZ NOT NULL,
           last_error_category TEXT NOT NULL
         )`,
        `CREATE TABLE IF NOT EXISTS mint_quote_reconciliation (
           mint_quote_id BIGINT PRIMARY KEY REFERENCES mint_quotes(id) ON DELETE CASCADE,
           last_checked_at TIMESTAMPTZ,
           next_check_at TIMESTAMPTZ NOT NULL,
           not_found_count INTEGER NOT NULL DEFAULT 0,
           last_result TEXT NOT NULL
         )`,
        "CREATE INDEX IF NOT EXISTS idx_mint_quote_reconciliation_due ON mint_quote_reconciliation(next_check_at)",
      ],
      sqlite: [
        `CREATE TABLE IF NOT EXISTS mint_quote_mint_retries (
           mint_url TEXT PRIMARY KEY,
           failure_count INTEGER NOT NULL,
           next_attempt_at TEXT NOT NULL,
           last_failure_at TEXT NOT NULL,
           last_error_category TEXT NOT NULL
         )`,
        `CREATE TABLE IF NOT EXISTS mint_quote_reconciliation (
           mint_quote_id INTEGER PRIMARY KEY REFERENCES mint_quotes(id) ON DELETE CASCADE,
           last_checked_at TEXT,
           next_check_at TEXT NOT NULL,
           not_found_count INTEGER NOT NULL DEFAULT 0,
           last_result TEXT NOT NULL
         )`,
        "CREATE INDEX IF NOT EXISTS idx_mint_quote_reconciliation_due ON mint_quote_reconciliation(next_check_at)",
      ],
    },
  },
];
